"""Initial schema

Revision ID: 0e75593ba950
Revises: 95c50aafb89a
Create Date: 2026-07-21 11:54:25.263703

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0e75593ba950"
down_revision: Union[str, Sequence[str], None] = "95c50aafb89a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
