"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiFetch, errorMessage } from "@/lib/api";
import { formatDateTime } from "@/lib/datetime";
import { istLogStart, highlightLogText } from "@/lib/log-search";
import { useKubernetesContexts } from "@/hooks/use-kubernetes";
import { PageHeading } from "@/components/ui/page-heading";
import { Table } from "@/components/ui/table";
import { ResourceState } from "@/components/ui/resource-state";

type Job={investigation_status?:string;id:string;state:string;stage:string;context:string;request:{namespace:string;resource_name?:string;resource_type:string};investigation_id?:string;error?:string;queued_at:string};
type Investigation={id:string;namespace:string;resource_name:string;cluster:string;created_at:string};
type Timeline={items:{at:string;kind:string;title:string;resource:string;detail:string}[];source:string};
type Change={id:string;state:string;deployment:string;context:string;diff:string;history:{time:string;event:string}[]};
type Book={id:string;name:string;checks:string[]};
type Alert={state:string;occurrences_in_recent_100:number;acknowledged_at?:string;id:string;title:string;severity:string;namespace:string;resource:string;context:string;investigation_id:string;at:string;notified_at?:string};
type Audit={id:string;actor:string;method:string;path:string;status:number;at:string};
type Graph={context:string;namespace:string;captured_at:string;nodes:{id:string;kind:string;name:string;status:string}[];edges:{from:string;to:string;relation:string}[]};
type Archive={cluster:string;namespace:string;pod:string;rows:{timestamp:string;line:string;labels:Record<string,string>}[];limit_reached:boolean};
const control="rounded-md border border-border bg-background px-3 py-2 text-sm disabled:opacity-40";
const sections=['Jobs','Archive','Timeline','Relationships','Changes','Runbooks','Alerts','Audit'] as const;
export default function OperationsPage(){
 const client=useQueryClient();const contexts=useKubernetesContexts();
 const [tab,setTab]=useState<string>('Jobs');const [ns,setNs]=useState('default');const [context,setContext]=useState('');const [name,setName]=useState('');const [kind,setKind]=useState('deployment');
 const [investigation,setInvestigation]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [output,setOutput]=useState<unknown>(null);
 const [archiveCluster,setArchiveCluster]=useState('');const [archiveContainer,setArchiveContainer]=useState('');
 const [start,setStart]=useState('');const [end,setEnd]=useState('');const [text,setText]=useState('');const [archive,setArchive]=useState<Archive|null>(null);const [logPage,setLogPage]=useState(0);
 const [graph,setGraph]=useState<Graph|null>(null);const [selected,setSelected]=useState('');const [bookName,setBookName]=useState('');const [book,setBook]=useState('image-pull');const [proposal,setProposal]=useState('');
 const activeContext=context||contexts.data?.current_context||'';
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get('investigation')){setInvestigation(p.get('investigation')!);setTab('Timeline');}},[]);
 const capability=useQuery({queryKey:['operations-capabilities'],queryFn:()=>apiFetch<{role:string;actor:string;archive_configured:boolean;notifications_configured:boolean}>('/v1/operations/capabilities'),retry:false});
 const jobs=useQuery({queryKey:['operations-jobs'],queryFn:()=>apiFetch<Job[]>('/v1/operations/jobs'),refetchInterval:3000,enabled:tab==='Jobs'});
 const invs=useQuery({queryKey:['operations-investigations'],queryFn:()=>apiFetch<{items:Investigation[]}>('/v1/investigations?page_size=100'),refetchInterval:15000});
 const timeline=useQuery({queryKey:['operations-timeline',investigation],queryFn:()=>apiFetch<Timeline>(`/v1/operations/timeline/${investigation}`),enabled:!!investigation&&tab==='Timeline'});
 const changes=useQuery({queryKey:['operations-changes',investigation],queryFn:()=>apiFetch<Change[]>(`/v1/operations/changes/${investigation}`),enabled:!!investigation&&['Changes','Runbooks'].includes(tab)});
 const books=useQuery({queryKey:['operations-runbooks'],queryFn:()=>apiFetch<Book[]>('/v1/operations/runbooks'),enabled:tab==='Runbooks'});
 const alerts=useQuery({queryKey:['operations-alerts'],queryFn:()=>apiFetch<Alert[]>('/v1/operations/alerts'),enabled:tab==='Alerts',refetchInterval:10000});
 const audits=useQuery({queryKey:['operations-audit'],queryFn:()=>apiFetch<Audit[]>('/v1/operations/audit'),enabled:tab==='Audit',retry:false});
 async function action(fn:()=>Promise<unknown>,message='Done'){setBusy(true);setError('');setNotice('');try{const result=await fn();setNotice(message);await client.invalidateQueries({queryKey:['operations-jobs']});await client.invalidateQueries({queryKey:['operations-runbooks']});await client.invalidateQueries({queryKey:['operations-alerts']});return result;}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 const post=(path:string,body:unknown={})=>apiFetch('/v1/operations/'+path,{method:'POST',body:JSON.stringify(body)});
 function changeTab(value:string){setTab(value);setError('');setNotice('');setOutput(null);}
 const queryError=capability.error||invs.error||(tab==='Jobs'?jobs.error:tab==='Timeline'?timeline.error:tab==='Changes'?changes.error:tab==='Runbooks'?books.error||changes.error:tab==='Alerts'?alerts.error:tab==='Audit'?audits.error:null);
 const targetFields=<><label className="grid gap-1 text-xs">Cluster<select aria-label="Operations cluster" className={control} value={activeContext} onChange={e=>{setContext(e.target.value);setGraph(null);setArchive(null);}}>{contexts.data?.contexts.map(c=><option key={c}>{c}</option>)}</select></label><label className="grid gap-1 text-xs">Namespace<input className={control} value={ns} onChange={e=>setNs(e.target.value)} /></label></>;
 return <><PageHeading title="Operations" actions={<span className="text-xs text-muted-foreground">{capability.data?.actor} · {capability.data?.role}</span>} />
 <nav aria-label="Operations sections" className="mb-5 flex flex-wrap gap-2">{sections.map(s=><button key={s} onClick={()=>changeTab(s)} aria-pressed={tab===s} className={`${control} ${tab===s?'bg-primary text-primary-foreground':''}`}>{s}</button>)}</nav>
 <ResourceState isLoading={false} error={queryError} />
 {error&&<p role="alert" className="mb-3 text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="mb-3 text-sm text-muted-foreground">{notice}</p>}
 {['Timeline','Changes','Runbooks'].includes(tab)&&<label className="mb-4 grid max-w-3xl gap-2 text-sm">Investigation<select className={control} value={investigation} onChange={e=>{setInvestigation(e.target.value);setProposal('');setOutput(null);}}><option value="">Select a saved investigation</option>{invs.data?.items.map(i=><option key={i.id} value={i.id}>{i.cluster} · {i.namespace}/{i.resource_name} · {formatDateTime(i.created_at)}</option>)}</select></label>}
 <section className="surface-card rounded-xl border bg-card p-5 space-y-4">
 {tab==='Jobs'&&<>
 <div className="flex flex-wrap items-end gap-3">{targetFields}<label className="grid gap-1 text-xs">Type<select className={control} value={kind} onChange={e=>setKind(e.target.value)}>{['deployment','pod','service','namespace'].map(k=><option key={k}>{k}</option>)}</select></label>{kind!=='namespace'&&<label className="grid gap-1 text-xs">Resource<input className={control} value={name} onChange={e=>setName(e.target.value)} /></label>}<button className={control} disabled={busy||!activeContext||!ns||(kind!=='namespace'&&!name)} onClick={()=>action(()=>post('jobs',{context:activeContext,namespace:ns,resource_type:kind,resource_name:kind==='namespace'?ns:name,log_tail:200}), 'Queued. You can leave this page.')}>{busy?'Queuing…':'Queue investigation'}</button></div>
 <Table paginate><thead><tr>{['Resource','Cluster','Status','Progress','Queued','Actions'].map(s=><th className="p-3 text-left text-xs" key={s}>{s}</th>)}</tr></thead><tbody>{jobs.data?.map(j=><tr key={j.id}><td className="p-3">{j.request.namespace}/{j.request.resource_name}</td><td className="max-w-56 break-all p-3 text-xs">{j.context}</td><td className="p-3">{j.state}</td><td className="p-3 text-sm">{j.error||j.stage}{j.investigation_status ? " · "+j.investigation_status : ""}</td><td className="p-3 text-xs">{formatDateTime(j.queued_at)}</td><td className="p-3">{j.investigation_id&&<Link className="text-primary" href={'/investigations/'+j.investigation_id}>Open result</Link>}</td></tr>)}</tbody></Table>
 {!jobs.data?.length&&<p className="text-sm text-muted-foreground">No queued investigations yet.</p>}
 </>}
 {tab==='Archive'&&<>
 {!capability.data?.archive_configured&&<p className="text-sm text-amber-700 dark:text-amber-300">Archive not connected. Configure Loki and your log collector.</p>}
 <div className="flex flex-wrap items-end gap-3">{targetFields}<label className="grid gap-1 text-xs">Archive cluster label<input aria-label="Archive cluster label" placeholder={activeContext||"Cluster label value"} className={control} value={archiveCluster} onChange={e=>setArchiveCluster(e.target.value)} /></label><label className="grid gap-1 text-xs">Container (optional)<input className={control} value={archiveContainer} onChange={e=>setArchiveContainer(e.target.value)} /></label><label className="grid gap-1 text-xs">Pod (optional)<input className={control} value={name} onChange={e=>setName(e.target.value)} /></label><label className="grid gap-1 text-xs">From (IST)<input type="datetime-local" className={control} value={start} onChange={e=>setStart(e.target.value)} /></label><label className="grid gap-1 text-xs">To (IST)<input type="datetime-local" className={control} value={end} onChange={e=>setEnd(e.target.value)} /></label><input aria-label="Archive search" placeholder="Search text…" className={control} value={text} onChange={e=>setText(e.target.value)} /><button className={control} disabled={busy||!start||!end||!(archiveCluster||activeContext)||!ns||!capability.data?.archive_configured} onClick={()=>action(async()=>{const data=await post('archive',{cluster:archiveCluster||activeContext,namespace:ns,pod:name,container:archiveContainer,start:istLogStart(start),end:istLogStart(end),text,limit:5000}) as Archive;setArchive(data);setLogPage(0);},'Archive loaded')}>Search archive</button></div>
 {archive&&<><p className="text-xs text-muted-foreground">{archive.cluster} · {archive.namespace}/{archive.pod||"all pods"} · {archive.rows.length} lines{archive.limit_reached?' · Limit reached; narrow the time range.':''}</p><pre className="log-content">{archive.rows.slice(logPage*500,(logPage+1)*500).map((r,i)=><span key={i}>{formatDateTime(new Date(Number(BigInt(r.timestamp)/BigInt(1000000))).toISOString())}{'  '}{highlightLogText(r.line,text,false,false).map((v,k)=>v.highlight?<mark key={k}>{v.text}</mark>:v.text)}{'\n'}</span>)}</pre><div className="flex items-center gap-3"><button className={control} disabled={!logPage} onClick={()=>setLogPage(logPage-1)}>Previous</button><span className="text-xs">Page {logPage+1} / {Math.max(1,Math.ceil(archive.rows.length/500))}</span><button className={control} disabled={(logPage+1)*500>=archive.rows.length} onClick={()=>setLogPage(logPage+1)}>Next</button></div></>}
 </>}
 {tab==='Timeline'&&<>{timeline.data?.items.map((e,i)=><div key={i} className="border-l-2 border-primary/30 py-2 pl-4"><div className="text-xs text-muted-foreground">{formatDateTime(e.at)} · {e.kind}</div><p className="text-sm font-medium">{e.title} <span className="font-normal text-muted-foreground">{e.resource}</span></p>{e.detail&&<details className="text-xs"><summary>Evidence</summary><p className="whitespace-pre-wrap pt-2">{e.detail}</p></details>}</div>)}{!investigation&&<p className="text-sm text-muted-foreground">Choose an investigation.</p>}{timeline.data&&<p className="text-xs text-muted-foreground">{timeline.data.source}</p>}</>}
 {tab==='Relationships'&&<><div className="flex flex-wrap items-end gap-3">{targetFields}<button className={control} disabled={busy||!ns||!activeContext} onClick={()=>action(async()=>{const data=await apiFetch<Graph>(`/v1/operations/relationships?${new URLSearchParams({context:activeContext,namespace:ns})}`);setGraph(data);setSelected(data.nodes[0]?.id||'');},'Relationships loaded')}>Load relationships</button></div>{graph&&<><p className="text-xs text-muted-foreground">{graph.context} · {graph.namespace} · {formatDateTime(graph.captured_at)}</p><select aria-label="Relationship resource" className={`${control} max-w-full`} value={selected} onChange={e=>setSelected(e.target.value)}>{graph.nodes.map(n=><option value={n.id} key={n.id}>{n.kind}/{n.name}</option>)}</select><div className="grid gap-4 md:grid-cols-3"><div className="space-y-2"><h3 className="text-xs uppercase text-muted-foreground">Incoming</h3>{graph.edges.filter(e=>e.to===selected).map((e,i)=><button key={i} className={`${control} block w-full text-left`} onClick={()=>setSelected(e.from)}>{graph.nodes.find(n=>n.id===e.from)?.name}<span className="block text-xs text-muted-foreground">{e.relation} →</span></button>)}</div><div className="rounded-xl border border-primary/30 bg-primary/5 p-5"><p className="text-xs">{graph.nodes.find(n=>n.id===selected)?.kind}</p><p className="break-all font-semibold">{graph.nodes.find(n=>n.id===selected)?.name}</p><p className="mt-2 text-sm">{graph.nodes.find(n=>n.id===selected)?.status}</p></div><div className="space-y-2"><h3 className="text-xs uppercase text-muted-foreground">Outgoing</h3>{graph.edges.filter(e=>e.from===selected).map((e,i)=><button key={i} className={`${control} block w-full text-left`} onClick={()=>setSelected(e.to)}><span className="block text-xs text-muted-foreground">{e.relation} →</span>{graph.nodes.find(n=>n.id===e.to)?.name}</button>)}</div></div></>}</>}
 {tab==='Changes'&&<>{changes.data?.map(c=><details key={c.id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm">{c.deployment} · {c.state}</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap text-xs">{c.diff||'Assessment only; no proposed changes.'}</pre><div className="mt-3 flex gap-3"><button className={control} disabled={busy||!['APPLIED','APPLIED_UNCONFIRMED','ROLLED_BACK','ROLLED_BACK_UNCONFIRMED'].includes(c.state)} onClick={()=>action(async()=>setOutput(await post('fixes/'+c.id+'/verify')),'Verification saved')}>Verify live health</button><button className={control} disabled={busy} onClick={()=>action(async()=>setOutput(await apiFetch('/v1/operations/fixes/'+c.id+'/verifications')),'Saved checks loaded')}>Verification history</button></div>{c.history.map((h,i)=><p key={i} className="mt-2 text-xs text-muted-foreground">{formatDateTime(h.time)} · {h.event}</p>)}</details>)}{!changes.data?.length&&<p className="text-sm text-muted-foreground">No fix proposals for this investigation.</p>}</>}
 {tab==='Runbooks'&&<><div className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs">Runbook<select className={control} value={book} onChange={e=>setBook(e.target.value)}>{books.data?.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="grid gap-1 text-xs">Assessment / proposal<select className={control} value={proposal} onChange={e=>setProposal(e.target.value)}><option value="">Select a proposal</option>{changes.data?.map(c=><option key={c.id} value={c.id}>{c.deployment} · {c.state} · {c.id.slice(0,8)}</option>)}</select></label><button className={control} disabled={busy||!proposal} onClick={()=>action(async()=>setOutput(await post('runbooks/'+book+'/run',{proposal_id:proposal})),'Checks saved. Open the AI assessment to reassess.')}>Run read-only checks</button></div><p className="text-xs text-muted-foreground">{books.data?.find(b=>b.id===book)?.checks.join(' → ')}</p><details className="text-sm"><summary>Save a runbook</summary><div className="mt-3 flex flex-wrap gap-3"><input aria-label="Runbook name" className={control} placeholder="Runbook name" value={bookName} onChange={e=>setBookName(e.target.value)} /><button className={control} disabled={busy||bookName.length<3} onClick={()=>action(()=>post('runbooks',{name:bookName,checks:books.data?.find(b=>b.id===book)?.checks}),'Runbook saved')}>Save selected checks</button></div></details>{investigation&&<Link className="inline-block text-sm text-primary" href={'/investigations/'+investigation}>Open AI assessment →</Link>}</>}
 {tab==='Alerts'&&<><p className="text-xs text-muted-foreground">High/critical findings from completed investigations. No continuous cluster monitoring.</p>{alerts.data?.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><Link className="text-sm font-medium text-primary" href={'/investigations/'+a.investigation_id}>{a.title}</Link><p className="text-xs text-muted-foreground">{a.context} · {a.namespace}/{a.resource} · {formatDateTime(a.at)} · {a.occurrences_in_recent_100} recent occurrences</p></div><button className={control} disabled={busy||a.state!=="OPEN"||!capability.data?.notifications_configured} onClick={()=>action(()=>post('alerts/'+a.id+'/notify'),'Notification delivered')}>{a.notified_at?'Delivered':a.state==='DELIVERY_UNKNOWN'?'Delivery unknown':'Send notification'}</button><button className={control} disabled={busy||!!a.acknowledged_at} onClick={()=>action(()=>post('alerts/'+a.id+'/acknowledge'),'Acknowledged')}>{a.acknowledged_at?'Acknowledged':'Acknowledge'}</button></div>)}{!alerts.data?.length&&<p className="text-sm">No alerts yet.</p>}</>}
 {tab==='Audit'&&<Table paginate><thead><tr>{['Time','Actor','Method','Path','Status'].map(s=><th key={s} className="p-3 text-left text-xs">{s}</th>)}</tr></thead><tbody>{audits.data?.map(a=><tr key={a.id}><td className="p-3 text-xs">{formatDateTime(a.at)}</td><td className="p-3">{a.actor}</td><td className="p-3">{a.method}</td><td className="max-w-xl break-all p-3 text-xs">{a.path}</td><td className="p-3">{a.status}</td></tr>)}</tbody></Table>}
 {output!=null&&<details open><summary className="text-sm">Results</summary><pre className="log-content log-wrap mt-3">{JSON.stringify(output,null,2)}</pre></details>}
 </section></>;
}
